import {Item} from "./dto/item";

export const DUMMY_DATA: Array<Item> = [
  new Item("I001",
    "https://m.media-amazon.com/images/I/71gtHnQGfQL._AC_UL320_.jpg",
    "TOZO T6 True Wireless Earbuds Bluetooth Headphones Touch Control with Wireless Charging Case IPX8 Waterproof Stereo Earphones",
    3,
    299,
    5),
  new Item("I002",
    "https://m.media-amazon.com/images/I/514yxmJNlqL._AC_UL320_.jpg",
    "Fitbit Versa 2 Health and Fitness Smartwatch with Heart Rate, Music, Alexa Built-In, Sleep and Swim Tracking, Black/Carbon",
    4,
    199,
    10),
  new Item("I003",
    "https://m.media-amazon.com/images/I/71o8Q5XJS5L._AC_UL320_.jpg",
    "Sony WH-1000XM4 Wireless Industry Leading Noise Canceling Overhead Headphones with Mic for Phone-Call and Alexa Voice Control",
    3,
    100,
    7),
  new Item("I004",
    "https://m.media-amazon.com/images/I/51DBPso+nkS._AC_UL320_.jpg",
    "for iPhone 12 Selfie Ring Light Case (Green),Akcoo 5 Light Models LED Luminous Ringlight Cover with Built-in Battery",
    1,
    999,
    17),
  new Item("I005",
    "https://m.media-amazon.com/images/I/61d5F64UDpL._AC_UL320_.jpg",
    "JBL FLIP 4 - Waterproof Portable Bluetooth Speaker - Black",
    5,
    29,
    5),
  new Item("I006",
    "https://m.media-amazon.com/images/I/71ic26eWeLL._AC_UL320_.jpg",
    "Original HP 67 Black/Tri-color Ink Cartridges (2-pack) | Works with HP DeskJet 1255, 2700, 4100 Series, HP ENVY 6000, 6400 Series",
    3,
    9,
    14),
  new Item("I007",
    "https://m.media-amazon.com/images/I/61-gVbDQMXL._AC_UL320_.jpg",
    "12\" Selfie Ring Light with Stand for iPhone Android, Selfie Light Ring YouTube Video Tiktok Makeup Photography Live",
    4,
    9,
    14)
];
